name: Manual Trigger for Staging Build Ok
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch to build'
        required: true
      prNumber:
        description: 'PR number (optional)'
        required: false
